var annotated_dup =
[
    [ "moodycamel", "db/dc8/namespacemoodycamel.html", [
      [ "details", "d6/d0f/namespacemoodycamel_1_1details.html", [
        [ "thread_id_converter", "d2/d23/structmoodycamel_1_1details_1_1thread__id__converter.html", "d2/d23/structmoodycamel_1_1details_1_1thread__id__converter" ],
        [ "identity", "da/def/structmoodycamel_1_1details_1_1identity.html", "da/def/structmoodycamel_1_1details_1_1identity" ],
        [ "const_numeric_max", "d8/d7d/structmoodycamel_1_1details_1_1const__numeric__max.html", "d8/d7d/structmoodycamel_1_1details_1_1const__numeric__max" ],
        [ "max_align_t", "d9/d3b/unionmoodycamel_1_1details_1_1max__align__t.html", "d9/d3b/unionmoodycamel_1_1details_1_1max__align__t" ],
        [ "ConcurrentQueueProducerTypelessBase", "d2/ddf/structmoodycamel_1_1details_1_1ConcurrentQueueProducerTypelessBase.html", "d2/ddf/structmoodycamel_1_1details_1_1ConcurrentQueueProducerTypelessBase" ],
        [ "_hash_32_or_64", "d6/de8/structmoodycamel_1_1details_1_1__hash__32__or__64.html", "d6/de8/structmoodycamel_1_1details_1_1__hash__32__or__64" ],
        [ "_hash_32_or_64< 1 >", "dd/ddb/structmoodycamel_1_1details_1_1__hash__32__or__64_3_011_01_4.html", "dd/ddb/structmoodycamel_1_1details_1_1__hash__32__or__64_3_011_01_4" ],
        [ "hash_32_or_64", "df/d6e/structmoodycamel_1_1details_1_1hash__32__or__64.html", null ],
        [ "nomove_if", "dd/df0/structmoodycamel_1_1details_1_1nomove__if.html", "dd/df0/structmoodycamel_1_1details_1_1nomove__if" ],
        [ "nomove_if< false >", "d3/dd9/structmoodycamel_1_1details_1_1nomove__if_3_01false_01_4.html", "d3/dd9/structmoodycamel_1_1details_1_1nomove__if_3_01false_01_4" ],
        [ "is_trivially_destructible", "d8/d2c/structmoodycamel_1_1details_1_1is__trivially__destructible.html", null ],
        [ "ThreadExitListener", "da/da8/structmoodycamel_1_1details_1_1ThreadExitListener.html", "da/da8/structmoodycamel_1_1details_1_1ThreadExitListener" ],
        [ "ThreadExitNotifier", "df/d23/classmoodycamel_1_1details_1_1ThreadExitNotifier.html", "df/d23/classmoodycamel_1_1details_1_1ThreadExitNotifier" ],
        [ "static_is_lock_free_num", "dc/d06/structmoodycamel_1_1details_1_1static__is__lock__free__num.html", null ],
        [ "static_is_lock_free_num< signed char >", "d3/dfe/structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01signed_01char_01_4.html", null ],
        [ "static_is_lock_free_num< short >", "d4/dd1/structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01short_01_4.html", null ],
        [ "static_is_lock_free_num< int >", "d1/d0b/structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01int_01_4.html", null ],
        [ "static_is_lock_free_num< long >", "d6/d70/structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01_4.html", null ],
        [ "static_is_lock_free_num< long long >", "de/da5/structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01long_01_4.html", null ],
        [ "static_is_lock_free", "d0/d15/structmoodycamel_1_1details_1_1static__is__lock__free.html", null ],
        [ "static_is_lock_free< bool >", "d2/da0/structmoodycamel_1_1details_1_1static__is__lock__free_3_01bool_01_4.html", null ],
        [ "static_is_lock_free< U * >", "dc/d62/structmoodycamel_1_1details_1_1static__is__lock__free_3_01U_01_5_01_4.html", null ]
      ] ],
      [ "ConcurrentQueueDefaultTraits", "d3/d55/structmoodycamel_1_1ConcurrentQueueDefaultTraits.html", "d3/d55/structmoodycamel_1_1ConcurrentQueueDefaultTraits" ],
      [ "ConcurrentQueue", "d8/dc8/classmoodycamel_1_1ConcurrentQueue.html", "d8/dc8/classmoodycamel_1_1ConcurrentQueue" ],
      [ "BlockingConcurrentQueue", "db/dea/classmoodycamel_1_1BlockingConcurrentQueue.html", null ],
      [ "ProducerToken", "d1/dbb/structmoodycamel_1_1ProducerToken.html", "d1/dbb/structmoodycamel_1_1ProducerToken" ],
      [ "ConsumerToken", "de/deb/structmoodycamel_1_1ConsumerToken.html", "de/deb/structmoodycamel_1_1ConsumerToken" ]
    ] ],
    [ "SatNet", "da/d8c/namespaceSatNet.html", [
      [ "Address", "d9/d27/classSatNet_1_1Address.html", "d9/d27/classSatNet_1_1Address" ],
      [ "AppInterface", "d8/d47/classSatNet_1_1AppInterface.html", "d8/d47/classSatNet_1_1AppInterface" ],
      [ "BeamScheduler", "df/d1b/classSatNet_1_1BeamScheduler.html", "df/d1b/classSatNet_1_1BeamScheduler" ],
      [ "BitsCollector", "d0/d77/classSatNet_1_1BitsCollector.html", "d0/d77/classSatNet_1_1BitsCollector" ],
      [ "Channel", "d9/d45/classSatNet_1_1Channel.html", "d9/d45/classSatNet_1_1Channel" ],
      [ "CnoEstimator", "d8/dad/classSatNet_1_1CnoEstimator.html", "d8/dad/classSatNet_1_1CnoEstimator" ],
      [ "Config", "d4/d2f/classSatNet_1_1Config.html", "d4/d2f/classSatNet_1_1Config" ],
      [ "ConstantPositionMobilityModel", "d9/dd1/classSatNet_1_1ConstantPositionMobilityModel.html", "d9/dd1/classSatNet_1_1ConstantPositionMobilityModel" ],
      [ "CtrlMsg", "db/d13/classSatNet_1_1CtrlMsg.html", "db/d13/classSatNet_1_1CtrlMsg" ],
      [ "DummyMsg", "d5/d2f/classSatNet_1_1DummyMsg.html", "d5/d2f/classSatNet_1_1DummyMsg" ],
      [ "LogonCtrlMsg", "dd/d70/classSatNet_1_1LogonCtrlMsg.html", "dd/d70/classSatNet_1_1LogonCtrlMsg" ],
      [ "LogoffCtrlMsg", "d6/d03/classSatNet_1_1LogoffCtrlMsg.html", "d6/d03/classSatNet_1_1LogoffCtrlMsg" ],
      [ "LogonResponseCtrlMsg", "df/dac/classSatNet_1_1LogonResponseCtrlMsg.html", "df/dac/classSatNet_1_1LogonResponseCtrlMsg" ],
      [ "CapacityRequestCtrlMsg", "d1/dc7/classSatNet_1_1CapacityRequestCtrlMsg.html", "d1/dc7/classSatNet_1_1CapacityRequestCtrlMsg" ],
      [ "TbtpCtrlMsg", "d8/da3/classSatNet_1_1TbtpCtrlMsg.html", "d8/da3/classSatNet_1_1TbtpCtrlMsg" ],
      [ "HeartbeatMsg", "db/d10/classSatNet_1_1HeartbeatMsg.html", "db/d10/classSatNet_1_1HeartbeatMsg" ],
      [ "HandoverMsg", "d1/de6/classSatNet_1_1HandoverMsg.html", "d1/de6/classSatNet_1_1HandoverMsg" ],
      [ "DisconnectMsg", "d6/d99/classSatNet_1_1DisconnectMsg.html", "d6/d99/classSatNet_1_1DisconnectMsg" ],
      [ "HandoverNotificationMsg", "db/d91/classSatNet_1_1HandoverNotificationMsg.html", "db/d91/classSatNet_1_1HandoverNotificationMsg" ],
      [ "DamaState", "d6/dc8/structSatNet_1_1DamaState.html", "d6/dc8/structSatNet_1_1DamaState" ],
      [ "Dama", "d5/dc0/classSatNet_1_1Dama.html", "d5/dc0/classSatNet_1_1Dama" ],
      [ "DeviceGW", "d1/d6b/classSatNet_1_1DeviceGW.html", "d1/d6b/classSatNet_1_1DeviceGW" ],
      [ "DeviceNCC", "dc/d12/classSatNet_1_1DeviceNCC.html", "dc/d12/classSatNet_1_1DeviceNCC" ],
      [ "DeviceNccInf", "da/d20/classSatNet_1_1DeviceNccInf.html", "da/d20/classSatNet_1_1DeviceNccInf" ],
      [ "DeviceSat", "dd/d8c/classSatNet_1_1DeviceSat.html", "dd/d8c/classSatNet_1_1DeviceSat" ],
      [ "DeviceUT", "de/db0/classSatNet_1_1DeviceUT.html", "de/db0/classSatNet_1_1DeviceUT" ],
      [ "Frame", "d3/d23/classSatNet_1_1Frame.html", "d3/d23/classSatNet_1_1Frame" ],
      [ "TimeSlotConf", "d8/d3c/classSatNet_1_1TimeSlotConf.html", "d8/d3c/classSatNet_1_1TimeSlotConf" ],
      [ "FrameConf", "d8/da6/classSatNet_1_1FrameConf.html", "d8/da6/classSatNet_1_1FrameConf" ],
      [ "GwLlc", "d7/d77/classSatNet_1_1GwLlc.html", "d7/d77/classSatNet_1_1GwLlc" ],
      [ "GwMac", "d2/dca/classSatNet_1_1GwMac.html", "d2/dca/classSatNet_1_1GwMac" ],
      [ "GwNetDev", "d7/dc7/classSatNet_1_1GwNetDev.html", "d7/dc7/classSatNet_1_1GwNetDev" ],
      [ "GwPhy", "df/d72/classSatNet_1_1GwPhy.html", "df/d72/classSatNet_1_1GwPhy" ],
      [ "HandoverModule", "d3/da5/classSatNet_1_1HandoverModule.html", "d3/da5/classSatNet_1_1HandoverModule" ],
      [ "LinkManagement", "d3/d4a/classSatNet_1_1LinkManagement.html", "d3/d4a/classSatNet_1_1LinkManagement" ],
      [ "LOG", "dc/d08/classSatNet_1_1LOG.html", "dc/d08/classSatNet_1_1LOG" ],
      [ "ILog", "d9/dd0/classSatNet_1_1ILog.html", "d9/dd0/classSatNet_1_1ILog" ],
      [ "SyncLog", "de/d3c/classSatNet_1_1SyncLog.html", "de/d3c/classSatNet_1_1SyncLog" ],
      [ "LooFadingModel", "d7/d37/classSatNet_1_1LooFadingModel.html", "d7/d37/classSatNet_1_1LooFadingModel" ],
      [ "LowerLayerService", "df/d50/classSatNet_1_1LowerLayerService.html", "df/d50/classSatNet_1_1LowerLayerService" ],
      [ "MobilityModel", "d2/d7d/classSatNet_1_1MobilityModel.html", "d2/d7d/classSatNet_1_1MobilityModel" ],
      [ "NccCore", "db/d64/classSatNet_1_1NccCore.html", "db/d64/classSatNet_1_1NccCore" ],
      [ "NccLlc", "d1/dfa/classSatNet_1_1NccLlc.html", "d1/dfa/classSatNet_1_1NccLlc" ],
      [ "NccMac", "d2/dc8/classSatNet_1_1NccMac.html", "d2/dc8/classSatNet_1_1NccMac" ],
      [ "NccNetDev", "de/d1b/classSatNet_1_1NccNetDev.html", "de/d1b/classSatNet_1_1NccNetDev" ],
      [ "NccPhy", "d7/d88/classSatNet_1_1NccPhy.html", "d7/d88/classSatNet_1_1NccPhy" ],
      [ "Packet", "db/ddc/classSatNet_1_1Packet.html", "db/ddc/classSatNet_1_1Packet" ],
      [ "PacketTracer", "d3/db8/classSatNet_1_1PacketTracer.html", "d3/db8/classSatNet_1_1PacketTracer" ],
      [ "Tag", "da/dc9/classSatNet_1_1Tag.html", "da/dc9/classSatNet_1_1Tag" ],
      [ "CtrlMsgTag", "d1/d12/classSatNet_1_1CtrlMsgTag.html", "d1/d12/classSatNet_1_1CtrlMsgTag" ],
      [ "AddrTag", "d7/dd2/classSatNet_1_1AddrTag.html", "d7/dd2/classSatNet_1_1AddrTag" ],
      [ "E2EAddressTag", "d4/de7/classSatNet_1_1E2EAddressTag.html", "d4/de7/classSatNet_1_1E2EAddressTag" ],
      [ "MacAddressTag", "d8/de7/classSatNet_1_1MacAddressTag.html", "d8/de7/classSatNet_1_1MacAddressTag" ],
      [ "GroundStationTag", "de/d67/classSatNet_1_1GroundStationTag.html", "de/d67/classSatNet_1_1GroundStationTag" ],
      [ "TrcTag", "d1/d25/classSatNet_1_1TrcTag.html", "d1/d25/classSatNet_1_1TrcTag" ],
      [ "PacketIdTag", "d9/d50/classSatNet_1_1PacketIdTag.html", "d9/d50/classSatNet_1_1PacketIdTag" ],
      [ "SendTimeTag", "da/db7/classSatNet_1_1SendTimeTag.html", "da/db7/classSatNet_1_1SendTimeTag" ],
      [ "SegmentTag", "d4/d6d/classSatNet_1_1SegmentTag.html", "d4/d6d/classSatNet_1_1SegmentTag" ],
      [ "RoundRobinScheduler", "d9/d41/classSatNet_1_1RoundRobinScheduler.html", "d9/d41/classSatNet_1_1RoundRobinScheduler" ],
      [ "Queue", "d0/d16/classSatNet_1_1Queue.html", "d0/d16/classSatNet_1_1Queue" ],
      [ "RawQueue", "d5/de9/classSatNet_1_1RawQueue.html", "d5/de9/classSatNet_1_1RawQueue" ],
      [ "QueueLockFree", "db/df2/classSatNet_1_1QueueLockFree.html", "db/df2/classSatNet_1_1QueueLockFree" ],
      [ "RawQueueLockFree", "de/dea/classSatNet_1_1RawQueueLockFree.html", "de/dea/classSatNet_1_1RawQueueLockFree" ],
      [ "RandomAccessAllocationChannel", "db/db4/classSatNet_1_1RandomAccessAllocationChannel.html", "db/db4/classSatNet_1_1RandomAccessAllocationChannel" ],
      [ "RandomAccess", "dd/dec/classSatNet_1_1RandomAccess.html", "dd/dec/classSatNet_1_1RandomAccess" ],
      [ "RandomAccessConf", "dd/dfc/classSatNet_1_1RandomAccessConf.html", "dd/dfc/classSatNet_1_1RandomAccessConf" ],
      [ "RandomPositionMobilityModel", "db/d01/classSatNet_1_1RandomPositionMobilityModel.html", "db/d01/classSatNet_1_1RandomPositionMobilityModel" ],
      [ "RandomPositionMobilityModel2", "d7/ded/classSatNet_1_1RandomPositionMobilityModel2.html", "d7/ded/classSatNet_1_1RandomPositionMobilityModel2" ],
      [ "RequestManager", "d6/d37/classSatNet_1_1RequestManager.html", "d6/d37/classSatNet_1_1RequestManager" ],
      [ "BaseRoutingTable", "da/dfd/classSatNet_1_1BaseRoutingTable.html", "da/dfd/classSatNet_1_1BaseRoutingTable" ],
      [ "RoutingTableBase", "d4/d32/classSatNet_1_1RoutingTableBase.html", "d4/d32/classSatNet_1_1RoutingTableBase" ],
      [ "UtRoutingInfo", "dd/da1/structSatNet_1_1UtRoutingInfo.html", "dd/da1/structSatNet_1_1UtRoutingInfo" ],
      [ "UtRoutingTable", "da/d22/classSatNet_1_1UtRoutingTable.html", "da/d22/classSatNet_1_1UtRoutingTable" ],
      [ "GwRoutingInfo", "d1/d06/structSatNet_1_1GwRoutingInfo.html", "d1/d06/structSatNet_1_1GwRoutingInfo" ],
      [ "GwRoutingTable", "d2/d45/classSatNet_1_1GwRoutingTable.html", "d2/d45/classSatNet_1_1GwRoutingTable" ],
      [ "SatFeederPhy", "d5/d65/classSatNet_1_1SatFeederPhy.html", "d5/d65/classSatNet_1_1SatFeederPhy" ],
      [ "SatIsLPhy", "df/d7c/classSatNet_1_1SatIsLPhy.html", "df/d7c/classSatNet_1_1SatIsLPhy" ],
      [ "SatLlc", "d6/d5e/classSatNet_1_1SatLlc.html", "d6/d5e/classSatNet_1_1SatLlc" ],
      [ "SatMac", "d6/daa/classSatNet_1_1SatMac.html", "d6/daa/classSatNet_1_1SatMac" ],
      [ "SatNetDev", "d9/d23/classSatNet_1_1SatNetDev.html", "d9/d23/classSatNet_1_1SatNetDev" ],
      [ "SatUtPhy", "dc/ddf/classSatNet_1_1SatUtPhy.html", "dc/ddf/classSatNet_1_1SatUtPhy" ],
      [ "SocketManager", "d9/de5/classSatNet_1_1SocketManager.html", "d9/de5/classSatNet_1_1SocketManager" ],
      [ "SuperFrame", "df/da8/classSatNet_1_1SuperFrame.html", "df/da8/classSatNet_1_1SuperFrame" ],
      [ "SuperFrameConf", "de/d81/classSatNet_1_1SuperFrameConf.html", "de/d81/classSatNet_1_1SuperFrameConf" ],
      [ "Time", "dd/d48/classSatNet_1_1Time.html", "dd/d48/classSatNet_1_1Time" ],
      [ "Topology", "d7/dc5/classSatNet_1_1Topology.html", "d7/dc5/classSatNet_1_1Topology" ],
      [ "TrafficMsg", "da/db8/classSatNet_1_1TrafficMsg.html", "da/db8/classSatNet_1_1TrafficMsg" ],
      [ "UeApp", "dc/d91/classSatNet_1_1UeApp.html", "dc/d91/classSatNet_1_1UeApp" ],
      [ "UtApp", "da/d4c/classSatNet_1_1UtApp.html", "da/d4c/classSatNet_1_1UtApp" ],
      [ "UtLlc", "de/d93/classSatNet_1_1UtLlc.html", "de/d93/classSatNet_1_1UtLlc" ],
      [ "TxThreadPool", "d4/d45/classSatNet_1_1TxThreadPool.html", "d4/d45/classSatNet_1_1TxThreadPool" ],
      [ "TxScheduler", "df/d2f/classSatNet_1_1TxScheduler.html", "df/d2f/classSatNet_1_1TxScheduler" ],
      [ "UtMAC", "d3/d44/classSatNet_1_1UtMAC.html", "d3/d44/classSatNet_1_1UtMAC" ],
      [ "UtNetDev", "d7/d1c/classSatNet_1_1UtNetDev.html", "d7/d1c/classSatNet_1_1UtNetDev" ],
      [ "UtPhy", "db/d4c/classSatNet_1_1UtPhy.html", "db/d4c/classSatNet_1_1UtPhy" ],
      [ "Waveform", "d9/ddb/classSatNet_1_1Waveform.html", "d9/ddb/classSatNet_1_1Waveform" ],
      [ "WaveformConf", "de/d57/classSatNet_1_1WaveformConf.html", "de/d57/classSatNet_1_1WaveformConf" ]
    ] ]
];