var annotated_dup =
[
    [ "moodycamel", "namespacemoodycamel.html", [
      [ "details", "namespacemoodycamel_1_1details.html", [
        [ "thread_id_converter", "structmoodycamel_1_1details_1_1thread__id__converter.html", "structmoodycamel_1_1details_1_1thread__id__converter" ],
        [ "identity", "structmoodycamel_1_1details_1_1identity.html", "structmoodycamel_1_1details_1_1identity" ],
        [ "const_numeric_max", "structmoodycamel_1_1details_1_1const__numeric__max.html", "structmoodycamel_1_1details_1_1const__numeric__max" ],
        [ "max_align_t", "unionmoodycamel_1_1details_1_1max__align__t.html", "unionmoodycamel_1_1details_1_1max__align__t" ],
        [ "ConcurrentQueueProducerTypelessBase", "structmoodycamel_1_1details_1_1ConcurrentQueueProducerTypelessBase.html", "structmoodycamel_1_1details_1_1ConcurrentQueueProducerTypelessBase" ],
        [ "_hash_32_or_64", "structmoodycamel_1_1details_1_1__hash__32__or__64.html", "structmoodycamel_1_1details_1_1__hash__32__or__64" ],
        [ "_hash_32_or_64< 1 >", "structmoodycamel_1_1details_1_1__hash__32__or__64_3_011_01_4.html", "structmoodycamel_1_1details_1_1__hash__32__or__64_3_011_01_4" ],
        [ "hash_32_or_64", "structmoodycamel_1_1details_1_1hash__32__or__64.html", null ],
        [ "nomove_if", "structmoodycamel_1_1details_1_1nomove__if.html", "structmoodycamel_1_1details_1_1nomove__if" ],
        [ "nomove_if< false >", "structmoodycamel_1_1details_1_1nomove__if_3_01false_01_4.html", "structmoodycamel_1_1details_1_1nomove__if_3_01false_01_4" ],
        [ "is_trivially_destructible", "structmoodycamel_1_1details_1_1is__trivially__destructible.html", null ],
        [ "ThreadExitListener", "structmoodycamel_1_1details_1_1ThreadExitListener.html", "structmoodycamel_1_1details_1_1ThreadExitListener" ],
        [ "ThreadExitNotifier", "classmoodycamel_1_1details_1_1ThreadExitNotifier.html", "classmoodycamel_1_1details_1_1ThreadExitNotifier" ],
        [ "static_is_lock_free_num", "structmoodycamel_1_1details_1_1static__is__lock__free__num.html", null ],
        [ "static_is_lock_free_num< signed char >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01signed_01char_01_4.html", null ],
        [ "static_is_lock_free_num< short >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01short_01_4.html", null ],
        [ "static_is_lock_free_num< int >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01int_01_4.html", null ],
        [ "static_is_lock_free_num< long >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01_4.html", null ],
        [ "static_is_lock_free_num< long long >", "structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01long_01_4.html", null ],
        [ "static_is_lock_free", "structmoodycamel_1_1details_1_1static__is__lock__free.html", null ],
        [ "static_is_lock_free< bool >", "structmoodycamel_1_1details_1_1static__is__lock__free_3_01bool_01_4.html", null ],
        [ "static_is_lock_free< U * >", "structmoodycamel_1_1details_1_1static__is__lock__free_3_01U_01_5_01_4.html", null ]
      ] ],
      [ "ConcurrentQueueDefaultTraits", "structmoodycamel_1_1ConcurrentQueueDefaultTraits.html", "structmoodycamel_1_1ConcurrentQueueDefaultTraits" ],
      [ "ConcurrentQueue", "classmoodycamel_1_1ConcurrentQueue.html", "classmoodycamel_1_1ConcurrentQueue" ],
      [ "BlockingConcurrentQueue", "classmoodycamel_1_1BlockingConcurrentQueue.html", null ],
      [ "ProducerToken", "structmoodycamel_1_1ProducerToken.html", "structmoodycamel_1_1ProducerToken" ],
      [ "ConsumerToken", "structmoodycamel_1_1ConsumerToken.html", "structmoodycamel_1_1ConsumerToken" ]
    ] ],
    [ "tron", "namespacetron.html", [
      [ "Address", "classtron_1_1Address.html", "classtron_1_1Address" ],
      [ "AppInterface", "classtron_1_1AppInterface.html", "classtron_1_1AppInterface" ],
      [ "BeamScheduler", "classtron_1_1BeamScheduler.html", "classtron_1_1BeamScheduler" ],
      [ "BitsCollector", "classtron_1_1BitsCollector.html", "classtron_1_1BitsCollector" ],
      [ "Channel", "classtron_1_1Channel.html", "classtron_1_1Channel" ],
      [ "CnoEstimator", "classtron_1_1CnoEstimator.html", "classtron_1_1CnoEstimator" ],
      [ "Config", "classtron_1_1Config.html", "classtron_1_1Config" ],
      [ "ConstantPositionMobilityModel", "classtron_1_1ConstantPositionMobilityModel.html", "classtron_1_1ConstantPositionMobilityModel" ],
      [ "CtrlMsg", "classtron_1_1CtrlMsg.html", "classtron_1_1CtrlMsg" ],
      [ "DummyMsg", "classtron_1_1DummyMsg.html", "classtron_1_1DummyMsg" ],
      [ "LogonCtrlMsg", "classtron_1_1LogonCtrlMsg.html", "classtron_1_1LogonCtrlMsg" ],
      [ "LogoffCtrlMsg", "classtron_1_1LogoffCtrlMsg.html", "classtron_1_1LogoffCtrlMsg" ],
      [ "LogonResponseCtrlMsg", "classtron_1_1LogonResponseCtrlMsg.html", "classtron_1_1LogonResponseCtrlMsg" ],
      [ "CapacityRequestCtrlMsg", "classtron_1_1CapacityRequestCtrlMsg.html", "classtron_1_1CapacityRequestCtrlMsg" ],
      [ "TbtpCtrlMsg", "classtron_1_1TbtpCtrlMsg.html", "classtron_1_1TbtpCtrlMsg" ],
      [ "HeartbeatMsg", "classtron_1_1HeartbeatMsg.html", "classtron_1_1HeartbeatMsg" ],
      [ "HandoverMsg", "classtron_1_1HandoverMsg.html", "classtron_1_1HandoverMsg" ],
      [ "DisconnectMsg", "classtron_1_1DisconnectMsg.html", "classtron_1_1DisconnectMsg" ],
      [ "HandoverNotificationMsg", "classtron_1_1HandoverNotificationMsg.html", "classtron_1_1HandoverNotificationMsg" ],
      [ "DamaState", "structtron_1_1DamaState.html", "structtron_1_1DamaState" ],
      [ "Dama", "classtron_1_1Dama.html", "classtron_1_1Dama" ],
      [ "DeviceGW", "classtron_1_1DeviceGW.html", "classtron_1_1DeviceGW" ],
      [ "DeviceNCC", "classtron_1_1DeviceNCC.html", "classtron_1_1DeviceNCC" ],
      [ "DeviceNccInf", "classtron_1_1DeviceNccInf.html", "classtron_1_1DeviceNccInf" ],
      [ "DeviceSat", "classtron_1_1DeviceSat.html", "classtron_1_1DeviceSat" ],
      [ "DeviceUT", "classtron_1_1DeviceUT.html", "classtron_1_1DeviceUT" ],
      [ "Frame", "classtron_1_1Frame.html", "classtron_1_1Frame" ],
      [ "TimeSlotConf", "classtron_1_1TimeSlotConf.html", "classtron_1_1TimeSlotConf" ],
      [ "FrameConf", "classtron_1_1FrameConf.html", "classtron_1_1FrameConf" ],
      [ "GwLlc", "classtron_1_1GwLlc.html", "classtron_1_1GwLlc" ],
      [ "GwMac", "classtron_1_1GwMac.html", "classtron_1_1GwMac" ],
      [ "GwNetDev", "classtron_1_1GwNetDev.html", "classtron_1_1GwNetDev" ],
      [ "GwPhy", "classtron_1_1GwPhy.html", "classtron_1_1GwPhy" ],
      [ "HandoverModule", "classtron_1_1HandoverModule.html", "classtron_1_1HandoverModule" ],
      [ "LinkManagement", "classtron_1_1LinkManagement.html", "classtron_1_1LinkManagement" ],
      [ "LOG", "classtron_1_1LOG.html", "classtron_1_1LOG" ],
      [ "LooFadingModel", "classtron_1_1LooFadingModel.html", "classtron_1_1LooFadingModel" ],
      [ "LowerLayerService", "classtron_1_1LowerLayerService.html", "classtron_1_1LowerLayerService" ],
      [ "MobilityModel", "classtron_1_1MobilityModel.html", "classtron_1_1MobilityModel" ],
      [ "NccCore", "classtron_1_1NccCore.html", "classtron_1_1NccCore" ],
      [ "NccLlc", "classtron_1_1NccLlc.html", "classtron_1_1NccLlc" ],
      [ "NccMac", "classtron_1_1NccMac.html", "classtron_1_1NccMac" ],
      [ "NccNetDev", "classtron_1_1NccNetDev.html", "classtron_1_1NccNetDev" ],
      [ "NccPhy", "classtron_1_1NccPhy.html", "classtron_1_1NccPhy" ],
      [ "Packet", "classtron_1_1Packet.html", "classtron_1_1Packet" ],
      [ "PacketTracer", "classtron_1_1PacketTracer.html", "classtron_1_1PacketTracer" ],
      [ "Tag", "classtron_1_1Tag.html", "classtron_1_1Tag" ],
      [ "CtrlMsgTag", "classtron_1_1CtrlMsgTag.html", "classtron_1_1CtrlMsgTag" ],
      [ "AddrTag", "classtron_1_1AddrTag.html", "classtron_1_1AddrTag" ],
      [ "E2EAddressTag", "classtron_1_1E2EAddressTag.html", "classtron_1_1E2EAddressTag" ],
      [ "MacAddressTag", "classtron_1_1MacAddressTag.html", "classtron_1_1MacAddressTag" ],
      [ "GroundStationTag", "classtron_1_1GroundStationTag.html", "classtron_1_1GroundStationTag" ],
      [ "TrcTag", "classtron_1_1TrcTag.html", "classtron_1_1TrcTag" ],
      [ "PacketIdTag", "classtron_1_1PacketIdTag.html", "classtron_1_1PacketIdTag" ],
      [ "SendTimeTag", "classtron_1_1SendTimeTag.html", "classtron_1_1SendTimeTag" ],
      [ "SegmentTag", "classtron_1_1SegmentTag.html", "classtron_1_1SegmentTag" ],
      [ "RoundRobinScheduler", "classtron_1_1RoundRobinScheduler.html", "classtron_1_1RoundRobinScheduler" ],
      [ "Queue", "classtron_1_1Queue.html", "classtron_1_1Queue" ],
      [ "RawQueue", "classtron_1_1RawQueue.html", "classtron_1_1RawQueue" ],
      [ "QueueLockFree", "classtron_1_1QueueLockFree.html", "classtron_1_1QueueLockFree" ],
      [ "RawQueueLockFree", "classtron_1_1RawQueueLockFree.html", "classtron_1_1RawQueueLockFree" ],
      [ "RandomAccessAllocationChannel", "classtron_1_1RandomAccessAllocationChannel.html", "classtron_1_1RandomAccessAllocationChannel" ],
      [ "RandomAccess", "classtron_1_1RandomAccess.html", "classtron_1_1RandomAccess" ],
      [ "RandomAccessConf", "classtron_1_1RandomAccessConf.html", "classtron_1_1RandomAccessConf" ],
      [ "RandomPositionMobilityModel", "classtron_1_1RandomPositionMobilityModel.html", "classtron_1_1RandomPositionMobilityModel" ],
      [ "RandomPositionMobilityModel2", "classtron_1_1RandomPositionMobilityModel2.html", "classtron_1_1RandomPositionMobilityModel2" ],
      [ "RequestManager", "classtron_1_1RequestManager.html", "classtron_1_1RequestManager" ],
      [ "BaseRoutingTable", "classtron_1_1BaseRoutingTable.html", "classtron_1_1BaseRoutingTable" ],
      [ "RoutingTableBase", "classtron_1_1RoutingTableBase.html", "classtron_1_1RoutingTableBase" ],
      [ "UtRoutingInfo", "structtron_1_1UtRoutingInfo.html", "structtron_1_1UtRoutingInfo" ],
      [ "UtRoutingTable", "classtron_1_1UtRoutingTable.html", "classtron_1_1UtRoutingTable" ],
      [ "GwRoutingInfo", "structtron_1_1GwRoutingInfo.html", "structtron_1_1GwRoutingInfo" ],
      [ "GwRoutingTable", "classtron_1_1GwRoutingTable.html", "classtron_1_1GwRoutingTable" ],
      [ "SatFeederPhy", "classtron_1_1SatFeederPhy.html", "classtron_1_1SatFeederPhy" ],
      [ "SatIsLPhy", "classtron_1_1SatIsLPhy.html", "classtron_1_1SatIsLPhy" ],
      [ "SatLlc", "classtron_1_1SatLlc.html", "classtron_1_1SatLlc" ],
      [ "SatMac", "classtron_1_1SatMac.html", "classtron_1_1SatMac" ],
      [ "SatNetDev", "classtron_1_1SatNetDev.html", "classtron_1_1SatNetDev" ],
      [ "SatUtPhy", "classtron_1_1SatUtPhy.html", "classtron_1_1SatUtPhy" ],
      [ "SocketManager", "classtron_1_1SocketManager.html", "classtron_1_1SocketManager" ],
      [ "SuperFrame", "classtron_1_1SuperFrame.html", "classtron_1_1SuperFrame" ],
      [ "SuperFrameConf", "classtron_1_1SuperFrameConf.html", "classtron_1_1SuperFrameConf" ],
      [ "Time", "classtron_1_1Time.html", "classtron_1_1Time" ],
      [ "Topology", "classtron_1_1Topology.html", "classtron_1_1Topology" ],
      [ "TrafficMsg", "classtron_1_1TrafficMsg.html", "classtron_1_1TrafficMsg" ],
      [ "UeApp", "classtron_1_1UeApp.html", "classtron_1_1UeApp" ],
      [ "UtApp", "classtron_1_1UtApp.html", "classtron_1_1UtApp" ],
      [ "UtLlc", "classtron_1_1UtLlc.html", "classtron_1_1UtLlc" ],
      [ "TxThreadPool", "classtron_1_1TxThreadPool.html", "classtron_1_1TxThreadPool" ],
      [ "TxScheduler", "classtron_1_1TxScheduler.html", "classtron_1_1TxScheduler" ],
      [ "UtMAC", "classtron_1_1UtMAC.html", "classtron_1_1UtMAC" ],
      [ "UtNetDev", "classtron_1_1UtNetDev.html", "classtron_1_1UtNetDev" ],
      [ "UtPhy", "classtron_1_1UtPhy.html", "classtron_1_1UtPhy" ],
      [ "Waveform", "classtron_1_1Waveform.html", "classtron_1_1Waveform" ],
      [ "WaveformConf", "classtron_1_1WaveformConf.html", "classtron_1_1WaveformConf" ]
    ] ]
];