var annotated_dup =
[
    [ "moodycamel", "db/dc8/namespacemoodycamel.html", [
      [ "details", "d6/d0f/namespacemoodycamel_1_1details.html", [
        [ "thread_id_converter", "d2/d23/structmoodycamel_1_1details_1_1thread__id__converter.html", "d2/d23/structmoodycamel_1_1details_1_1thread__id__converter" ],
        [ "identity", "da/def/structmoodycamel_1_1details_1_1identity.html", "da/def/structmoodycamel_1_1details_1_1identity" ],
        [ "const_numeric_max", "d8/d7d/structmoodycamel_1_1details_1_1const__numeric__max.html", "d8/d7d/structmoodycamel_1_1details_1_1const__numeric__max" ],
        [ "max_align_t", "d9/d3b/unionmoodycamel_1_1details_1_1max__align__t.html", "d9/d3b/unionmoodycamel_1_1details_1_1max__align__t" ],
        [ "ConcurrentQueueProducerTypelessBase", "d2/ddf/structmoodycamel_1_1details_1_1ConcurrentQueueProducerTypelessBase.html", "d2/ddf/structmoodycamel_1_1details_1_1ConcurrentQueueProducerTypelessBase" ],
        [ "_hash_32_or_64", "d6/de8/structmoodycamel_1_1details_1_1__hash__32__or__64.html", "d6/de8/structmoodycamel_1_1details_1_1__hash__32__or__64" ],
        [ "_hash_32_or_64< 1 >", "dd/ddb/structmoodycamel_1_1details_1_1__hash__32__or__64_3_011_01_4.html", "dd/ddb/structmoodycamel_1_1details_1_1__hash__32__or__64_3_011_01_4" ],
        [ "hash_32_or_64", "df/d6e/structmoodycamel_1_1details_1_1hash__32__or__64.html", null ],
        [ "nomove_if", "dd/df0/structmoodycamel_1_1details_1_1nomove__if.html", "dd/df0/structmoodycamel_1_1details_1_1nomove__if" ],
        [ "nomove_if< false >", "d3/dd9/structmoodycamel_1_1details_1_1nomove__if_3_01false_01_4.html", "d3/dd9/structmoodycamel_1_1details_1_1nomove__if_3_01false_01_4" ],
        [ "is_trivially_destructible", "d8/d2c/structmoodycamel_1_1details_1_1is__trivially__destructible.html", null ],
        [ "ThreadExitListener", "da/da8/structmoodycamel_1_1details_1_1ThreadExitListener.html", "da/da8/structmoodycamel_1_1details_1_1ThreadExitListener" ],
        [ "ThreadExitNotifier", "df/d23/classmoodycamel_1_1details_1_1ThreadExitNotifier.html", "df/d23/classmoodycamel_1_1details_1_1ThreadExitNotifier" ],
        [ "static_is_lock_free_num", "dc/d06/structmoodycamel_1_1details_1_1static__is__lock__free__num.html", null ],
        [ "static_is_lock_free_num< signed char >", "d3/dfe/structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01signed_01char_01_4.html", null ],
        [ "static_is_lock_free_num< short >", "d4/dd1/structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01short_01_4.html", null ],
        [ "static_is_lock_free_num< int >", "d1/d0b/structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01int_01_4.html", null ],
        [ "static_is_lock_free_num< long >", "d6/d70/structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01_4.html", null ],
        [ "static_is_lock_free_num< long long >", "de/da5/structmoodycamel_1_1details_1_1static__is__lock__free__num_3_01long_01long_01_4.html", null ],
        [ "static_is_lock_free", "d0/d15/structmoodycamel_1_1details_1_1static__is__lock__free.html", null ],
        [ "static_is_lock_free< bool >", "d2/da0/structmoodycamel_1_1details_1_1static__is__lock__free_3_01bool_01_4.html", null ],
        [ "static_is_lock_free< U * >", "dc/d62/structmoodycamel_1_1details_1_1static__is__lock__free_3_01U_01_5_01_4.html", null ]
      ] ],
      [ "ConcurrentQueueDefaultTraits", "d3/d55/structmoodycamel_1_1ConcurrentQueueDefaultTraits.html", "d3/d55/structmoodycamel_1_1ConcurrentQueueDefaultTraits" ],
      [ "ConcurrentQueue", "d8/dc8/classmoodycamel_1_1ConcurrentQueue.html", "d8/dc8/classmoodycamel_1_1ConcurrentQueue" ],
      [ "BlockingConcurrentQueue", "db/dea/classmoodycamel_1_1BlockingConcurrentQueue.html", null ],
      [ "ProducerToken", "d1/dbb/structmoodycamel_1_1ProducerToken.html", "d1/dbb/structmoodycamel_1_1ProducerToken" ],
      [ "ConsumerToken", "de/deb/structmoodycamel_1_1ConsumerToken.html", "de/deb/structmoodycamel_1_1ConsumerToken" ]
    ] ],
    [ "tron", "d1/db5/namespacetron.html", [
      [ "Address", "d2/de6/classtron_1_1Address.html", "d2/de6/classtron_1_1Address" ],
      [ "AppInterface", "d2/de9/classtron_1_1AppInterface.html", "d2/de9/classtron_1_1AppInterface" ],
      [ "BeamScheduler", "db/df8/classtron_1_1BeamScheduler.html", "db/df8/classtron_1_1BeamScheduler" ],
      [ "BitsCollector", "d1/dfe/classtron_1_1BitsCollector.html", "d1/dfe/classtron_1_1BitsCollector" ],
      [ "Channel", "dd/d09/classtron_1_1Channel.html", "dd/d09/classtron_1_1Channel" ],
      [ "CnoEstimator", "d7/d1b/classtron_1_1CnoEstimator.html", "d7/d1b/classtron_1_1CnoEstimator" ],
      [ "Config", "da/d70/classtron_1_1Config.html", "da/d70/classtron_1_1Config" ],
      [ "ConstantPositionMobilityModel", "d9/de9/classtron_1_1ConstantPositionMobilityModel.html", "d9/de9/classtron_1_1ConstantPositionMobilityModel" ],
      [ "CtrlMsg", "d6/d61/classtron_1_1CtrlMsg.html", "d6/d61/classtron_1_1CtrlMsg" ],
      [ "DummyMsg", "d2/d7e/classtron_1_1DummyMsg.html", "d2/d7e/classtron_1_1DummyMsg" ],
      [ "LogonCtrlMsg", "d5/d61/classtron_1_1LogonCtrlMsg.html", "d5/d61/classtron_1_1LogonCtrlMsg" ],
      [ "LogoffCtrlMsg", "d0/de0/classtron_1_1LogoffCtrlMsg.html", "d0/de0/classtron_1_1LogoffCtrlMsg" ],
      [ "LogonResponseCtrlMsg", "de/dda/classtron_1_1LogonResponseCtrlMsg.html", "de/dda/classtron_1_1LogonResponseCtrlMsg" ],
      [ "CapacityRequestCtrlMsg", "d6/d81/classtron_1_1CapacityRequestCtrlMsg.html", "d6/d81/classtron_1_1CapacityRequestCtrlMsg" ],
      [ "TbtpCtrlMsg", "d9/d8e/classtron_1_1TbtpCtrlMsg.html", "d9/d8e/classtron_1_1TbtpCtrlMsg" ],
      [ "HeartbeatMsg", "d6/d4e/classtron_1_1HeartbeatMsg.html", "d6/d4e/classtron_1_1HeartbeatMsg" ],
      [ "HandoverMsg", "d8/d96/classtron_1_1HandoverMsg.html", "d8/d96/classtron_1_1HandoverMsg" ],
      [ "DisconnectMsg", "d1/dd7/classtron_1_1DisconnectMsg.html", "d1/dd7/classtron_1_1DisconnectMsg" ],
      [ "HandoverNotificationMsg", "d1/d93/classtron_1_1HandoverNotificationMsg.html", "d1/d93/classtron_1_1HandoverNotificationMsg" ],
      [ "DamaState", "dc/dc9/structtron_1_1DamaState.html", "dc/dc9/structtron_1_1DamaState" ],
      [ "Dama", "d5/df5/classtron_1_1Dama.html", "d5/df5/classtron_1_1Dama" ],
      [ "DeviceGW", "d8/d1e/classtron_1_1DeviceGW.html", "d8/d1e/classtron_1_1DeviceGW" ],
      [ "DeviceNCC", "da/d9b/classtron_1_1DeviceNCC.html", "da/d9b/classtron_1_1DeviceNCC" ],
      [ "DeviceNccInf", "dc/db4/classtron_1_1DeviceNccInf.html", "dc/db4/classtron_1_1DeviceNccInf" ],
      [ "DeviceSat", "d8/dd7/classtron_1_1DeviceSat.html", "d8/dd7/classtron_1_1DeviceSat" ],
      [ "DeviceUT", "da/d42/classtron_1_1DeviceUT.html", "da/d42/classtron_1_1DeviceUT" ],
      [ "Frame", "df/dfe/classtron_1_1Frame.html", "df/dfe/classtron_1_1Frame" ],
      [ "TimeSlotConf", "d1/d4d/classtron_1_1TimeSlotConf.html", "d1/d4d/classtron_1_1TimeSlotConf" ],
      [ "FrameConf", "d0/dd8/classtron_1_1FrameConf.html", "d0/dd8/classtron_1_1FrameConf" ],
      [ "GwLlc", "d1/d94/classtron_1_1GwLlc.html", "d1/d94/classtron_1_1GwLlc" ],
      [ "GwMac", "d8/d55/classtron_1_1GwMac.html", "d8/d55/classtron_1_1GwMac" ],
      [ "GwNetDev", "d3/d78/classtron_1_1GwNetDev.html", "d3/d78/classtron_1_1GwNetDev" ],
      [ "GwPhy", "d6/d07/classtron_1_1GwPhy.html", "d6/d07/classtron_1_1GwPhy" ],
      [ "HandoverModule", "d9/d65/classtron_1_1HandoverModule.html", "d9/d65/classtron_1_1HandoverModule" ],
      [ "LinkManagement", "d2/dd7/classtron_1_1LinkManagement.html", "d2/dd7/classtron_1_1LinkManagement" ],
      [ "LOG", "dc/db8/classtron_1_1LOG.html", "dc/db8/classtron_1_1LOG" ],
      [ "LooFadingModel", "d2/d86/classtron_1_1LooFadingModel.html", "d2/d86/classtron_1_1LooFadingModel" ],
      [ "LowerLayerService", "de/dcb/classtron_1_1LowerLayerService.html", "de/dcb/classtron_1_1LowerLayerService" ],
      [ "MobilityModel", "df/da1/classtron_1_1MobilityModel.html", "df/da1/classtron_1_1MobilityModel" ],
      [ "NccCore", "d9/d76/classtron_1_1NccCore.html", "d9/d76/classtron_1_1NccCore" ],
      [ "NccLlc", "df/dc1/classtron_1_1NccLlc.html", "df/dc1/classtron_1_1NccLlc" ],
      [ "NccMac", "d0/dbb/classtron_1_1NccMac.html", "d0/dbb/classtron_1_1NccMac" ],
      [ "NccNetDev", "dc/d5e/classtron_1_1NccNetDev.html", "dc/d5e/classtron_1_1NccNetDev" ],
      [ "NccPhy", "dc/d11/classtron_1_1NccPhy.html", "dc/d11/classtron_1_1NccPhy" ],
      [ "Packet", "db/dd8/classtron_1_1Packet.html", "db/dd8/classtron_1_1Packet" ],
      [ "PacketTracer", "d6/d4c/classtron_1_1PacketTracer.html", "d6/d4c/classtron_1_1PacketTracer" ],
      [ "Tag", "dc/d27/classtron_1_1Tag.html", "dc/d27/classtron_1_1Tag" ],
      [ "CtrlMsgTag", "d2/dd3/classtron_1_1CtrlMsgTag.html", "d2/dd3/classtron_1_1CtrlMsgTag" ],
      [ "AddrTag", "d1/de9/classtron_1_1AddrTag.html", "d1/de9/classtron_1_1AddrTag" ],
      [ "E2EAddressTag", "d7/d0b/classtron_1_1E2EAddressTag.html", "d7/d0b/classtron_1_1E2EAddressTag" ],
      [ "MacAddressTag", "d0/d2a/classtron_1_1MacAddressTag.html", "d0/d2a/classtron_1_1MacAddressTag" ],
      [ "GroundStationTag", "dd/d14/classtron_1_1GroundStationTag.html", "dd/d14/classtron_1_1GroundStationTag" ],
      [ "TrcTag", "dc/de7/classtron_1_1TrcTag.html", "dc/de7/classtron_1_1TrcTag" ],
      [ "PacketIdTag", "d5/d2a/classtron_1_1PacketIdTag.html", "d5/d2a/classtron_1_1PacketIdTag" ],
      [ "SendTimeTag", "d8/d8a/classtron_1_1SendTimeTag.html", "d8/d8a/classtron_1_1SendTimeTag" ],
      [ "SegmentTag", "df/d05/classtron_1_1SegmentTag.html", "df/d05/classtron_1_1SegmentTag" ],
      [ "RoundRobinScheduler", "d4/d6d/classtron_1_1RoundRobinScheduler.html", "d4/d6d/classtron_1_1RoundRobinScheduler" ],
      [ "Queue", "da/d95/classtron_1_1Queue.html", "da/d95/classtron_1_1Queue" ],
      [ "RawQueue", "d1/d47/classtron_1_1RawQueue.html", "d1/d47/classtron_1_1RawQueue" ],
      [ "QueueLockFree", "df/d3d/classtron_1_1QueueLockFree.html", "df/d3d/classtron_1_1QueueLockFree" ],
      [ "RawQueueLockFree", "d2/d99/classtron_1_1RawQueueLockFree.html", "d2/d99/classtron_1_1RawQueueLockFree" ],
      [ "RandomAccessAllocationChannel", "dc/d54/classtron_1_1RandomAccessAllocationChannel.html", "dc/d54/classtron_1_1RandomAccessAllocationChannel" ],
      [ "RandomAccess", "d7/d1a/classtron_1_1RandomAccess.html", "d7/d1a/classtron_1_1RandomAccess" ],
      [ "RandomAccessConf", "d9/dbe/classtron_1_1RandomAccessConf.html", "d9/dbe/classtron_1_1RandomAccessConf" ],
      [ "RandomPositionMobilityModel", "d5/d67/classtron_1_1RandomPositionMobilityModel.html", "d5/d67/classtron_1_1RandomPositionMobilityModel" ],
      [ "RandomPositionMobilityModel2", "d3/d92/classtron_1_1RandomPositionMobilityModel2.html", "d3/d92/classtron_1_1RandomPositionMobilityModel2" ],
      [ "RequestManager", "d3/d48/classtron_1_1RequestManager.html", "d3/d48/classtron_1_1RequestManager" ],
      [ "BaseRoutingTable", "d3/dce/classtron_1_1BaseRoutingTable.html", "d3/dce/classtron_1_1BaseRoutingTable" ],
      [ "RoutingTableBase", "d6/df4/classtron_1_1RoutingTableBase.html", "d6/df4/classtron_1_1RoutingTableBase" ],
      [ "UtRoutingInfo", "d3/daf/structtron_1_1UtRoutingInfo.html", "d3/daf/structtron_1_1UtRoutingInfo" ],
      [ "UtRoutingTable", "d2/d8f/classtron_1_1UtRoutingTable.html", "d2/d8f/classtron_1_1UtRoutingTable" ],
      [ "GwRoutingInfo", "da/dd2/structtron_1_1GwRoutingInfo.html", "da/dd2/structtron_1_1GwRoutingInfo" ],
      [ "GwRoutingTable", "d9/d0e/classtron_1_1GwRoutingTable.html", "d9/d0e/classtron_1_1GwRoutingTable" ],
      [ "SatFeederPhy", "d2/d9d/classtron_1_1SatFeederPhy.html", "d2/d9d/classtron_1_1SatFeederPhy" ],
      [ "SatIsLPhy", "df/d8c/classtron_1_1SatIsLPhy.html", "df/d8c/classtron_1_1SatIsLPhy" ],
      [ "SatLlc", "d6/d0e/classtron_1_1SatLlc.html", "d6/d0e/classtron_1_1SatLlc" ],
      [ "SatMac", "dd/d5a/classtron_1_1SatMac.html", "dd/d5a/classtron_1_1SatMac" ],
      [ "SatNetDev", "de/dc4/classtron_1_1SatNetDev.html", "de/dc4/classtron_1_1SatNetDev" ],
      [ "SatUtPhy", "d5/da6/classtron_1_1SatUtPhy.html", "d5/da6/classtron_1_1SatUtPhy" ],
      [ "SocketManager", "d2/d5b/classtron_1_1SocketManager.html", "d2/d5b/classtron_1_1SocketManager" ],
      [ "SuperFrame", "dc/d4a/classtron_1_1SuperFrame.html", "dc/d4a/classtron_1_1SuperFrame" ],
      [ "SuperFrameConf", "db/d70/classtron_1_1SuperFrameConf.html", "db/d70/classtron_1_1SuperFrameConf" ],
      [ "Time", "df/db5/classtron_1_1Time.html", "df/db5/classtron_1_1Time" ],
      [ "Topology", "d4/da9/classtron_1_1Topology.html", "d4/da9/classtron_1_1Topology" ],
      [ "TrafficMsg", "d3/daf/classtron_1_1TrafficMsg.html", "d3/daf/classtron_1_1TrafficMsg" ],
      [ "UeApp", "d2/d68/classtron_1_1UeApp.html", "d2/d68/classtron_1_1UeApp" ],
      [ "UtApp", "d9/da3/classtron_1_1UtApp.html", "d9/da3/classtron_1_1UtApp" ],
      [ "UtLlc", "dc/d4c/classtron_1_1UtLlc.html", "dc/d4c/classtron_1_1UtLlc" ],
      [ "TxThreadPool", "de/d37/classtron_1_1TxThreadPool.html", "de/d37/classtron_1_1TxThreadPool" ],
      [ "TxScheduler", "d1/d91/classtron_1_1TxScheduler.html", "d1/d91/classtron_1_1TxScheduler" ],
      [ "UtMAC", "d9/d15/classtron_1_1UtMAC.html", "d9/d15/classtron_1_1UtMAC" ],
      [ "UtNetDev", "de/df7/classtron_1_1UtNetDev.html", "de/df7/classtron_1_1UtNetDev" ],
      [ "UtPhy", "d6/d07/classtron_1_1UtPhy.html", "d6/d07/classtron_1_1UtPhy" ],
      [ "Waveform", "d7/d78/classtron_1_1Waveform.html", "d7/d78/classtron_1_1Waveform" ],
      [ "WaveformConf", "d7/d5b/classtron_1_1WaveformConf.html", "d7/d5b/classtron_1_1WaveformConf" ]
    ] ]
];